### ISSUE TITLE
src/poolboy.erl:16: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1 [JIRA: RIAK-1556]

### ISSUE THREAD

**Issue by Pumpapa** [basho/poolboy#4]
Trying to build https://github.com/michaelklishin/riak_core_cowboy_example, I hit upon

Compiled src/poolboy_sup.erl
compile: warnings being treated as errors
src/poolboy.erl:16: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
src/poolboy.erl:18: type queue/0 is deprecated and will be removed in OTP 18.0; use use queue:queue/0 or preferably queue:queue/1
make: **\* [compile] Error 1

Both removing warnings_as_errors or fixing the error as suggested in the warning work. Should I fix it check that in?

**Comment by marianoguerra** [comment]
here I provide a fix for this issue, let me know if you prefer a pull request:

https://github.com/marianoguerra/poolboy/commit/d3483e1ef8b5d12145fb5c11e5b2879c69b24960

**Comment by cmeiklejohn** [comment]
Oops, didn't see this.  Resolved by https://github.com/basho/poolboy/pull/9.
